package com.jspservletcookbook;

/*
  ** This file was automatically generated by EJBGen 2.11beta
  ** Build: 20021104-0000
*/

import javax.ejb.EJBLocalObject;

public interface AbbrevLocal extends EJBLocalObject {

     public String getAbbreviation(String state);
}
