package com.jspservletcookbook;


/*
  ** This file was automatically generated by EJBGen 2.11beta
  ** Build: 20021104-0000
*/

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import javax.ejb.FinderException;
import java.rmi.RemoteException;
import java.util.Collection;

public interface AbbrevHome extends EJBHome {

    Abbrev create() throws RemoteException, CreateException;

}
